import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/')
  await page.getByText('Reserve a table').click()
  await expect(page).toHaveURL('http://localhost:3000/reservations')
  await page.getByLabel('FIRST NAME:').click()
  await page.getByLabel('FIRST NAME:').fill('John')
  const firstName = page.locator('input[name=firstName]')
  await expect(firstName).toHaveValue('John')
  await page.getByLabel('LAST NAME:').click()
  await page.getByLabel('LAST NAME:').fill('Doe')
  const lastName = page.locator('input[name=lastName]')
  await expect(lastName).toHaveValue('Doe')
  await page.getByLabel('PHONE:').click()
  await page.getByLabel('PHONE:').fill('123-456-7890')
  const phone = page.locator('input[name=phone]')
  await expect(phone).toHaveValue('123-456-7890')
  await page.getByLabel('DATE:').click()
  await page.getByLabel('DATE:').fill('2024-09-13')
  const date = page.locator('input[name=date]')
  await expect(date).toHaveValue('2024-09-13')
  await page.getByLabel('TIME:').click()
  await page.getByLabel('TIME:').selectOption('6:30 PM')
  const time = page.locator('select[name=time]')
  await expect(time).toHaveValue('6:30 PM')
  await page.getByLabel('OCCASION:').click()
  await page.getByLabel('OCCASION:').selectOption('Birthday')
  const occasion = page.locator('select[name=occasion]')
  await expect(occasion).toHaveValue('Birthday')
  await page.getByLabel('NUMBER OF GUEST:').click()
  await page.getByLabel('NUMBER OF GUEST:').fill('5')
  const guestNum = page.locator('input[name=guestNum]')
  await expect(guestNum).toHaveValue('5')
  await page.getByLabel('NOTES:').click()
  await page.getByLabel('NOTES:').fill('This is a test!')
  const notes = page.locator('textarea[name=notes]')
  await expect(notes).toHaveValue('This is a test!')
})
