import type { Metadata } from "next";
import "./globals.css";
import { karla } from "./fonts";
import React from 'react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${karla.variable}`}>
      <body className="font-karla" >
        <main>{children}</main>
      </body>
    </html>
  );
}
